server:
  port: 9091

spring:
  application:
    name: fraud
  datasource:
    username: amigoscode
    url: jdbc:postgresql://localhost:5433/fraud
    password: amigoscode
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true